[package]
name = "efsim"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "render",
    "util",
]

[dependencies]
# Local dependencies
render = { path = "render" }
util = { path = "util" }
