[package]
name = "render"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.13.1"
pollster = "0.3.0"
rand = "0.8.5"
raw-window-handle = "0.5.2"
rayon = "1.8.0"
regex = "1.9.5"
winit = "0.28.6"
wgpu = "0.17.0"

# Local
util = { path = "../util" }
